### ISSUE TITLE
setup.py lists "python-termstyle", but it was renamed to "termstyle" by the author

### ISSUE THREAD

**Issue by daym** [JBKahn/rednose#12]
Your setup.py lists "python-termstyle" as dependency - however, the author renamed it to "termstyle". That means you pick up an old version.

I suggest modifying setup.py to use "termstyle" instead of "python-termstyle".

**Comment by JBKahn** [comment]
will do

**Comment by JBKahn** [comment]
PR created #13

**Comment by JBKahn** [comment]
merged.
