### ISSUE TITLE
Add LICENSE and MANIFEST

### ISSUE THREAD

**Issue by pmlandwehr** [JBKahn/rednose#18]
Hey-lo,

I'm building a version of `rednose` using [`conda`](http://conda.pydata.org/) for [conda-forge](http://conda-forge.github.io/). When possible, we include a link to the license file in the `meta.yaml` specification for the build; doing so requires the license be indexed in an explicit [`MANIFEST.in`](https://docs.python.org/2/distutils/sourcedist.html#manifest-related-options) file so that it gets included in the source distribution. Would you consider adding both a an actual license file and a `MANIFEST.in` that bundles the license in the next release? Also, can you please specify if you're using a [BSD 2-Clause](https://opensource.org/licenses/BSD-2-Clause) or a [BSD 3-Clause](https://opensource.org/licenses/BSD-3-Clause) license? "BSD" leaves it a bit ambiguous :(.

**Comment by JBKahn** [comment]
sure I'll get on this over the weekend.

**Comment by JBKahn** [comment]
Adding today, swapping to MIT.
