### ISSUE TITLE
no such option: --rednose

### ISSUE THREAD

**Issue by CostGranda** [JBKahn/rednose#21]
Hello, I'm tryng to use the _rednose_ plugin, but when I install it (pip3), _nose_ doesn't seem's to recognize it.

`nosetests version 1.3.7
`
```bash
    debian➜  test  ᐅ  nosetests --rednose
    Usage: nosetests [options]

    nosetests: error: no such option: --rednose
```
Thanks!

**Comment by JBKahn** [comment]
I think it's likely you installed rednose and nose on two different version of python maybe? I cannot reproduce this.

can you do a `pip3 list` and a `pip list`. I'm going to close this for now, re-open if it still is an issue/
