### ISSUE TITLE
Problem with skipped test on Jenkins (Build step 'Console output (build log) parsing' changed build result to FAILURE)

### ISSUE THREAD

**Issue by safo-bora** [JBKahn/rednose#6]
I have problem with skipped tests. (We use message from skipped test in output for test maintaining and can't hide them.)
For example we have failed test:

```
======================================================================
1) SKIP: Testing some feature
----------------------------------------------------------------------
   No Traceback
   Exception: http://jira:5000/browse/KA-123456

------------------------------------------
```

When I run it with jenkins I have failed BUILD because output parser defines **"Exception"**  in output.
It is better to use some other word, not "Exception" for skipped test.

_*\* And also is confused that this skipped message has RED color. Will be more better - blue_ 

**SOME SCREENSHOTS:**

![rednose](https://cloud.githubusercontent.com/assets/4173393/15476568/6564b622-2118-11e6-842c-53cc47e548be.png)

![rednose2](https://cloud.githubusercontent.com/assets/4173393/15476570/69476bd6-2118-11e6-981b-0084ce4e48f7.png)

**Comment by JBKahn** [comment]
You can have it not print out skip tests, it's one of the command line
options :) then you'll be fine.

**Comment by safo-bora** [comment]
Do you mean "--hide-skips" ? I didn't find some other option. 
But I need to show all this message because I have to see why we had skipped the test. And we need to see all skipped tests because we maintain them every day.

**Comment by JBKahn** [comment]
That's why I added the ability to print them. I can add different wording for skips, but for the moment you should hide them and I'll look at changing the wording.

**Comment by JBKahn** [comment]
`hide-skips` will be equivalent the old way of printing these results since they were not printed before the latest version. I might have time to look at this today or some time this week, at changing the wording.

**Comment by safo-bora** [comment]
Ok! Thanks! Will be very great!
Yes I know that previous version was without skipped message.
I just was working on showing all skipped message in output. And you at the same time did upgrade to version 1.1.1 with this possibility. 
It is very good upgrade but only one this problem with Jenkins is present. 

---

And could you please show skipped message with BLUE colour. 
We used to see only failed test with RED. We are afraid of RED in output)

**Comment by safo-bora** [comment]
Could you please say will you release new version with fix? 
Could you please give some estimates?

**Comment by JBKahn** [comment]
I'll try to do it by next week or the week after. I need to update the
tests to be proper tests rather than the hacky diff code I do now.

**Comment by safo-bora** [comment]
Ok :)

**Comment by JBKahn** [comment]
Changes released.

**Comment by safo-bora** [comment]
Works! Thanks!!

![rednose](https://cloud.githubusercontent.com/assets/4173393/15651989/cb039aa2-268b-11e6-9930-0cc8f75c1da4.png)
